// flow-typed signature: 5eac50d45bbfc23fc363b3512a382486
// flow-typed version: <<STUB>>/p5_v^0.6.1/flow_v0.73.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'p5'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'p5' {
  declare module.exports: any
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'p5/lib/addons/p5.dom' {
  declare module.exports: any
}

declare module 'p5/lib/addons/p5.dom.min' {
  declare module.exports: any
}

declare module 'p5/lib/addons/p5.sound' {
  declare module.exports: any
}

declare module 'p5/lib/addons/p5.sound.min' {
  declare module.exports: any
}

declare module 'p5/lib/p5' {
  declare module.exports: any
}

declare module 'p5/lib/p5.min' {
  declare module.exports: any
}

// Filename aliases
declare module 'p5/lib/addons/p5.dom.js' {
  declare module.exports: $Exports<'p5/lib/addons/p5.dom'>
}
declare module 'p5/lib/addons/p5.dom.min.js' {
  declare module.exports: $Exports<'p5/lib/addons/p5.dom.min'>
}
declare module 'p5/lib/addons/p5.sound.js' {
  declare module.exports: $Exports<'p5/lib/addons/p5.sound'>
}
declare module 'p5/lib/addons/p5.sound.min.js' {
  declare module.exports: $Exports<'p5/lib/addons/p5.sound.min'>
}
declare module 'p5/lib/p5.js' {
  declare module.exports: $Exports<'p5/lib/p5'>
}
declare module 'p5/lib/p5.min.js' {
  declare module.exports: $Exports<'p5/lib/p5.min'>
}
